import type { Episode, Podcast, WeeklySummary } from './types'

// ─────────────────────────────────────────────────────────────────────────────
// Mock data. Modelled on the client's actual lineup (WTF is with Nikhil Kamath,
// Business Breakdowns, The Latticework Podcast, Odd Lots, Masters in Business,
// Big Take, Bloomberg Surveillance, Bloomberg Businessweek, Bloomberg Intelligence)
// so the prototype reads like the real product. Swap this file's exports for live
// API responses without touching any component.
// ─────────────────────────────────────────────────────────────────────────────

export const PODCASTS: Podcast[] = [
  {
    id: 'wtf',
    title: 'WTF is with Nikhil Kamath',
    author: 'Nikhil Kamath',
    category: 'Business · Founders',
    description: `Zerodha co-founder Nikhil Kamath in candid, long-form conversations with founders, investors, and leaders on business, money, and ambition.`,
    cadence: 'Weekly',
    episodeCount: 62,
    source: 'youtube',
    color: '#e11d48',
    monogram: 'WT',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/ea/92/bc/ea92bcc1-d79e-b780-c431-be689efa819f/mza_6575857123336925418.jpeg/600x600bb.jpg',
    feedUrl: 'https://feeds.hubhopper.com/664690fdea0d7a6f61a052da119934d3.rss',
    tracked: true,
  },
  {
    id: 'businessbreakdowns',
    title: 'Business Breakdowns',
    author: 'Colossus | Investing & Business Podcasts',
    category: 'Investing',
    description: `Deep dives into individual businesses — how they work, how they make money, and what makes them tick — with operators and expert guests.`,
    cadence: 'Weekly',
    episodeCount: 214,
    source: 'podcast',
    color: '#0f766e',
    monogram: 'BB',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/97/90/91/979091f8-211b-a280-b12d-df99f7dbbd96/mza_7882909243651474210.jpg/600x600bb.jpg',
    feedUrl: 'https://feeds.megaphone.fm/breakdowns',
    tracked: true,
  },
  {
    id: 'latticework',
    title: 'The Latticework Podcast (MOI Global)',
    author: 'MOI Global',
    category: 'Value Investing',
    description: `MOI Global's conversations with leading value investors on multidisciplinary thinking, business quality, and the craft of long-term compounding.`,
    cadence: '1–2 / month',
    episodeCount: 88,
    source: 'youtube',
    color: '#7c3aed',
    monogram: 'LW',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts118/v4/f4/71/8d/f4718dde-8494-555c-6b6b-8b41ab9391e1/mza_4388135711105487281.jpg/600x600bb.jpg',
    feedUrl: 'https://feeds.soundcloud.com/users/soundcloud:users:320438167/sounds.rss',
    tracked: true,
  },
  {
    id: 'oddlots',
    title: 'Odd Lots',
    author: 'Bloomberg',
    category: 'Markets',
    description: `Bloomberg's Joe Weisenthal and Tracy Alloway go deep on the niche corners of markets, economics, and the plumbing of the financial system.`,
    cadence: '2–3 / week',
    episodeCount: 726,
    source: 'podcast',
    color: '#b3541e',
    monogram: 'OL',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/f3/99/6a/f3996a52-e4a4-bf0d-b7d6-e376c4058568/mza_15550359494736224565.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/8a94442e-5a74-4fa2-8b8d-ae27003a8d6b/982f5071-765c-403d-969d-ae27003a8d83/podcast.rss',
    tracked: true,
  },
  {
    id: 'mastersinbusiness',
    title: 'Masters in Business',
    author: 'Bloomberg',
    category: 'Investing',
    description: `Barry Ritholtz interviews the most influential people in finance and business about markets, investing, and the arc of their careers.`,
    cadence: 'Weekly',
    episodeCount: 564,
    source: 'podcast',
    color: '#1d4ed8',
    monogram: 'MB',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/34/d2/a0/34d2a06d-e4bd-4350-ade9-bc38a75d9077/mza_365911378155679487.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/4e4cd910-40a1-4619-a5f3-ae2b0012ffff/5873a3cb-298f-40bc-b71f-ae2b0013000d/podcast.rss',
    tracked: true,
  },
  {
    id: 'bigtake',
    title: 'Big Take',
    author: 'Bloomberg and iHeartPodcasts',
    category: 'News · Markets',
    description: `Bloomberg's flagship daily podcast, unpacking one big story shaping business, markets, and the global economy.`,
    cadence: 'Daily',
    episodeCount: 486,
    source: 'podcast',
    color: '#0891b2',
    monogram: 'BT',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/ac/01/b8/ac01b8bb-211e-0778-9f90-bb58122861ba/mza_11830189738414095793.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/825d4e29-b616-46f4-afd7-ae2b0013005c/8b1dd624-a026-43e9-8b57-ae2b00130066/podcast.rss',
    tracked: true,
  },
  {
    id: 'surveillance',
    title: 'Bloomberg Surveillance',
    author: 'Bloomberg',
    category: 'Markets · Macro',
    description: `Bloomberg's markets-and-economics morning show — real-time analysis of the forces moving global markets, with newsmaker interviews.`,
    cadence: 'Daily',
    episodeCount: 912,
    source: 'podcast',
    color: '#b91c1c',
    monogram: 'SV',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts116/v4/02/c5/36/02c5367b-22cc-2555-ff0c-d8a7981014ea/mza_17425960332446088310.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/8e704079-ca57-4eac-9741-ae27003e2b7f/9739700c-72c3-4176-ae55-ae27003e2b96/podcast.rss',
    tracked: true,
  },
  {
    id: 'businessweek',
    title: 'Bloomberg Businessweek',
    author: 'Bloomberg',
    category: 'Business',
    description: `Bloomberg Businessweek's conversations on the companies, people, and trends driving the business world.`,
    cadence: 'Daily',
    episodeCount: 803,
    source: 'podcast',
    color: '#111827',
    monogram: 'BW',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts221/v4/a1/6d/40/a16d4028-1fd8-abf0-cfd2-c59447c74c0a/mza_317399451927467704.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/3b082bbf-691d-443b-bc59-ae2b0012ff93/9222076a-d22a-4a9f-9d26-ae2b0012ffb4/podcast.rss',
    tracked: true,
  },
  {
    id: 'bloombergintel',
    title: 'Bloomberg Intelligence',
    author: 'Bloomberg',
    category: 'Research · Markets',
    description: `Bloomberg Intelligence analysts break down the data and research behind sectors, companies, and macro themes for professional investors.`,
    cadence: '2–3 / week',
    episodeCount: 301,
    source: 'podcast',
    color: '#0369a1',
    monogram: 'BI',
    artworkUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Podcasts211/v4/cd/3f/e6/cd3fe63c-5a08-7ff6-ff6c-32cdcd53411f/mza_15386103358990007192.jpg/600x600bb.jpg',
    feedUrl: 'https://www.omnycontent.com/d/playlist/e73c998e-6e60-432f-8610-ae210140c5b1/7f534b8c-9e91-429a-b102-ae3c00090c6d/0ad812bf-fd15-4012-a18c-ae3c00090c76/podcast.rss',
    tracked: true,
  },
]

// A small, neutral fallback set. The app loads real episodes live from each show's
// feed (server/feeds.ts); these seeds only surface when a live fetch is unavailable,
// and they double as sample data for the PDF/Word/email exporters. Each references a
// tracked show above. Real per-episode content is generated live at runtime.
export const EPISODES: Episode[] = [
  // Odd Lots — fully analysed seed (synthesis + insight + numbers + idea + highlights + Q&A).
  {
    id: 'ep-oddlots-grid',
    podcastId: 'oddlots',
    title: 'The Hidden Plumbing of the Treasury Market',
    publishedAt: '2026-06-02',
    durationSec: 3360,
    status: 'ready',
    signal: 'high',
    blurb: `Why the mechanics of Treasury issuance — auctions, primary dealers, and the repo market — quietly set the price of everything else.`,
    entities: {
      people: ['Joe Weisenthal', 'Tracy Alloway'],
      companies: ['U.S. Treasury', 'Federal Reserve'],
      themes: ['Treasury market', 'Repo', 'Liquidity', 'Rates'],
    },
    summary: {
      synthesis: [
        `Joe and Tracy unpack the **market plumbing** most investors never see: how Treasury auctions clear, how primary dealers warehouse the paper, and how the repo market finances all of it. The throughline is that **liquidity conditions in these pipes set the price of risk everywhere else** — when the plumbing seizes, it shows up in equities and credit long before the headlines.`,
        `The guest argues the post-2020 surge in issuance has **outgrown dealer balance-sheet capacity**, so small frictions now ripple further than they used to. The investable read: watch the plumbing, not just the Fed.`,
      ],
      highlights: [
        { id: 'h-ol-1', title: 'Issuance has outgrown dealer capacity', timestamp: '11:20', detail: `The stock of Treasuries has grown faster than the balance sheets meant to intermediate it — so ordinary frictions now move prices more than they did a decade ago.`, key: true },
        { id: 'h-ol-2', title: 'Repo is the real thermostat', timestamp: '24:40', detail: `Overnight funding rates, not the headline policy rate, are where stress first appears — the canary for the whole risk complex.`, key: true },
        { id: 'h-ol-3', title: 'Plumbing sets the price of everything', timestamp: '38:05', detail: `When financing the safe asset gets expensive, every other asset reprices in sympathy.` },
      ],
      qa: [
        { q: `Why watch repo instead of the Fed?`, a: `Because funding stress shows up in overnight rates days before it reaches the assets everyone actually trades — it's the earliest tell.` },
        { q: `What breaks first if issuance keeps climbing?`, a: `Dealer intermediation. When balance sheets are full, bid-ask widens and volatility rises — the plumbing, not policy, becomes the binding constraint.` },
      ],
      ideas: [
        {
          idea: `Own the intermediaries that get paid for balance sheet`,
          proponent: 'The guest',
          thesis: [
            `Ballooning issuance **rewards whoever can warehouse and finance it**`,
            `Scarcer balance-sheet capacity widens the spreads dealers earn`,
          ],
          kind: 'trade',
        },
      ],
      insight: {
        whatChanged: `Treasury issuance has grown faster than the dealer balance sheets that intermediate it, so market-plumbing frictions now transmit to risk assets more forcefully than in the prior cycle.`,
        whyItMatters: `If funding — not the policy rate — is the binding constraint, repo and dealer capacity become the leading indicators for equity and credit volatility.`,
        beneficiaries: [{ name: 'Primary dealers', why: 'wider intermediation spreads as balance-sheet capacity turns scarce' }],
        atRisk: [{ name: 'Levered rates strategies', why: 'funding-cost spikes hit carry trades first when repo tightens' }],
        diligenceQuestions: [
          `How much dealer balance-sheet capacity remains relative to the projected issuance calendar?`,
          `Which funding-market indicators lead equity volatility most reliably?`,
        ],
      },
      quantData: [
        { metric: 'Treasury market size', value: '~$28T', context: 'Roughly triple its pre-2015 level' },
        { metric: 'Primary dealer count', value: '24', context: 'Intermediating a far larger market than a decade ago' },
      ],
    },
  },
  // Masters in Business — summary-only seed (no pitched ideas / investable-insight block),
  // so the exporters correctly omit those sections.
  {
    id: 'ep-mib-brief',
    podcastId: 'mastersinbusiness',
    title: 'A Career in Compounding: Lessons from Five Decades',
    publishedAt: '2026-05-30',
    durationSec: 5400,
    status: 'ready',
    signal: 'normal',
    blurb: `A veteran allocator on process over prediction, the discipline of doing nothing, and what actually compounds over a career.`,
    entities: {
      people: ['Barry Ritholtz'],
      companies: [],
      themes: ['Compounding', 'Temperament', 'Process'],
    },
    summary: {
      synthesis: [
        `The guest's throughline is that **process beats prediction**: durable results come from a repeatable decision framework and the temperament to stick with it, not from calling the next macro turn. The rarest edge is **the discipline to do nothing** for long stretches.`,
        `Much of the conversation is about compounding — of capital, but also of reputation and relationships — and how small, consistent advantages dominate over a multi-decade horizon.`,
      ],
      highlights: [
        { id: 'h-mib-1', title: 'Process beats prediction', timestamp: '19:10', detail: `A repeatable framework you can hold through drawdowns outperforms any single well-timed call.`, key: true },
        { id: 'h-mib-2', title: 'The discipline of doing nothing', timestamp: '42:35', detail: `Most damage is self-inflicted — the hard, valuable skill is sitting still when there's nothing to do.`, key: true },
        { id: 'h-mib-3', title: 'Reputation compounds too', timestamp: '58:00', detail: `Trust built consistently over decades becomes its own kind of moat.` },
      ],
      qa: [
        { q: `What's the most underrated investing skill?`, a: `Temperament. The analysis is table stakes; the ability to not act on every impulse is what actually compounds.` },
        { q: `How should investors treat forecasts?`, a: `Lightly. Build a process that's robust to being wrong rather than one that depends on being right about the future.` },
      ],
    },
  },
]

export const WEEKLY: WeeklySummary = {
  id: 'wk-2026-05-30',
  rangeLabel: 'May 30 – June 5, 2026',
  episodeCount: 9,
  readMinutes: 11,
  overview: [
    `The throughline across the week was unmistakable: the AI debate has moved from "which model wins" to "what physically constrains the buildout." Stratechery reframed models as a commoditizing cost center while distribution stays scarce; Odd Lots put hard numbers on the real bottleneck — power, interconnection queues, and transformer lead times; and All-In turned both threads into a markets question about whether AI capex is a supercycle or a bubble.`,
    `On the investing side, Invest Like the Best and In Good Company circled the same idea from opposite ends of the size spectrum: durable returns come from owning the right thing for a very long time and staying liquid when others are forced to sell. Acquired's TSMC deep-dive supplied the concrete case study — process leadership that compounds, wrapped in geopolitical concentration risk.`,
    `If there's one synthesis: the market is repricing the un-sexy layer of the stack — power, foundries, distribution — and discounting the layer everyone was excited about a year ago, the models themselves.`,
  ],
  citations: [
    { index: 1, episodeId: 'ep-oddlots-grid', label: 'Odd Lots — The Grid Is the AI Bottleneck' },
    { index: 2, episodeId: 'ep-stratechery-agg', label: 'Stratechery — Aggregation Theory Meets AI' },
    { index: 3, episodeId: 'ep-allin-e184', label: 'All-In — E184: Is AI Capex a Bubble?' },
    { index: 4, episodeId: 'ep-iltb-compounders', label: 'Invest Like the Best — Compounders' },
    { index: 5, episodeId: 'ep-acquired-tsmc', label: 'Acquired — TSMC' },
  ],
  keyThemes: [
    {
      heading: 'Power, not silicon, is the binding constraint',
      points: [
        `**Interconnection queues gate the buildout**: permitted sites with signed interconnection agreements behave like call options on AI capacity, while the public queue can run a decade [1].`,
        `**Transformer and transmission supply is sold out for years**, so firm-power and grid-equipment names capture the scarcity the chipmakers can't [1] [3].`,
      ],
    },
    {
      heading: 'AI capex: supercycle or depreciation-driven mirage',
      points: [
        `**The depreciation schedule decides the debate**: at a 6-year GPU life the infra-margin math works; at 3 years much of the reported margin is fiction [3].`,
        `**Circular, vendor-funded demand flatters the real end-market**, the core of the bear case on the most levered names [3].`,
      ],
    },
    {
      heading: 'Value migrates to distribution and foundries',
      points: [
        `**Models are commoditizing** — durable value accrues to whoever owns distribution, not the frontier model [2].`,
        `**Process leadership compounds**: TSMC's ~90% leading-edge share is a moat and a single-point-of-failure the AI economy can't quickly diversify [5].`,
      ],
    },
  ],
  quantTable: [
    { metric: 'Interconnection queue', value: '~2,000 days', context: 'Time to connect new load in constrained regions [1]' },
    { metric: 'GPU useful life (bull vs bear)', value: '6 yrs vs 3 yrs', context: 'The swing factor in AI-infra margins [3]' },
    { metric: 'Transformer lead times', value: '2–3 years', context: 'Grid-equipment supply sold out [1]' },
    { metric: 'TSMC leading-edge share', value: '~90%', context: 'Concentration + single-point-of-failure risk [5]' },
  ],
  episodeReadouts: [
    {
      index: 1,
      episodeId: 'ep-oddlots-grid',
      episode: 'AI grid bottleneck',
      theme: 'Power, not chips, gates the AI buildout',
      evidence: 'Interconnection queues run ~2,000 days in constrained regions; transformer lead times are 2–3 years and grid-equipment supply is sold out [1].',
      interpretation: 'If power and interconnection — not GPUs — are the binding constraint, the durable value may sit with firm-power and grid-equipment names rather than the chipmakers.',
      namesSectors: 'Power equipment, grid, transformers, utilities, data-center power',
      confidence: 'Medium',
      action: 'Verify transformer order books and interconnection-queue data; assumes permitted sites command scarcity pricing.',
      questionsToVerify: ['Which projects have actually slipped on interconnection vs. chips?', 'Are transformer lead times confirmed across multiple OEMs?'],
    },
    {
      index: 2,
      episodeId: 'ep-stratechery-agg',
      episode: 'Aggregation theory + AI',
      theme: 'Models commoditize; distribution captures the value',
      evidence: 'Argues frontier models trend toward a cost center while distribution/aggregation stays scarce [2].',
      interpretation: 'This suggests value accrues to incumbents that own demand aggregation and distribution, not to model labs per se.',
      namesSectors: 'Hyperscalers, aggregators, software distribution',
      confidence: 'Low',
      action: 'Frame as a lens, not a trade; check gross-margin trajectory of model APIs vs. distribution platforms.',
      questionsToVerify: ['Are model API prices actually compressing?', 'Which distributors are converting AI into pricing power?'],
    },
    {
      index: 3,
      episodeId: 'ep-allin-e184',
      episode: 'AI capex bubble debate',
      theme: 'GPU depreciation decides the AI-infra margin story',
      evidence: 'Split panel: at a 6-year GPU life the infra-margin math works; at 3 years much of the reported margin is fiction [3].',
      interpretation: 'If accurate, the same revenue supports either a supercycle or a bubble depending purely on the depreciation assumption — the swing factor to track.',
      namesSectors: 'Nvidia, hyperscalers, AI infrastructure',
      confidence: 'Medium',
      action: 'Pull hyperscaler 10-K depreciation policies for GPUs; assumes useful-life disclosure is comparable across names.',
      questionsToVerify: ['What GPU useful life are the top hyperscalers actually booking?', 'How much of reported AI-infra margin flips at a 3-year schedule?'],
    },
    {
      index: 4,
      episodeId: 'ep-iltb-compounders',
      episode: 'Permanent capital',
      theme: 'Permanent capital turns time into alpha',
      evidence: 'Frames permanent-capital structures as able to stay liquid and buy when others are forced sellers [4].',
      interpretation: 'A useful mental model for insurance float + permanent capital; relevant to Berkshire/Markel/Fairfax-style balance sheets rather than a single ticker.',
      namesSectors: 'Insurers, permanent capital, asset managers',
      confidence: 'Low',
      action: 'Compare liability structure and investment latitude across permanent-capital insurers; monitor only.',
      questionsToVerify: ['Which insurers have the longest-duration, lowest-cost float?', 'Where does mandate flexibility actually differ?'],
    },
    {
      index: 5,
      episodeId: 'ep-acquired-tsmc',
      episode: 'TSMC',
      theme: 'Process leadership compounds; concentration is the risk',
      evidence: 'TSMC holds ~90% leading-edge share — process leadership compounds, but it is a single-point-of-failure concentration [5].',
      interpretation: 'This suggests durable pricing power offset by tail geopolitical risk; the bull/bear hinges on how that concentration is underwritten.',
      namesSectors: 'TSMC, semiconductors, foundry, semicap',
      confidence: 'Medium',
      action: 'Stress-test customer concentration and geopolitical scenarios; assumes leading-edge share persists.',
      questionsToVerify: ['How fast can Intel/Samsung close the leading-edge gap?', 'What is the realistic downside under a Taiwan supply shock?'],
    },
  ],
  shows: [
    {
      show: 'All-In',
      podcastId: 'allin',
      episodeIds: ['ep-allin-e184'],
      episodeCount: 1,
      ideas: [
        {
          idea: 'Long Nvidia (NVDA) into the capex supercycle',
          proponent: 'David Sacks',
          thesis: [`End-demand is real and **power-constrained**, not vendor-manufactured`, `A 6-year GPU life keeps infra margins durable`],
          kind: 'stock',
          episodeId: 'ep-allin-e184',
        },
        {
          idea: 'Fade the most levered AI names on circular financing',
          proponent: 'David Friedberg',
          thesis: [`Vendor-funded demand flatters the real end-market`, `A 3-year depreciation schedule would gut reported margins`],
          kind: 'trade',
          episodeId: 'ep-allin-e184',
        },
        {
          idea: 'The Fed cuts twice more in 2026',
          proponent: 'Chamath Palihapitiya',
          thesis: [`Disinflation is back on trend`, `A reopening IPO window signals easing financial conditions`],
          kind: 'macro',
          episodeId: 'ep-allin-e184',
        },
      ],
      takeaways: [
        { title: 'The depreciation argument', detail: `If GPUs are 6-year assets the AI-infra margin math works; if 3-year, much of the reported margin is fiction.` },
        { title: 'The IPO window is genuinely open', detail: `A handful of clean listings reset comps and pulled venture distributions forward for the first time in two years.` },
      ],
      questions: [`Is AI capex a supercycle or a bubble?`, `What depreciation schedule are hyperscalers really using for GPUs?`],
    },
    {
      show: 'Odd Lots',
      podcastId: 'oddlots',
      episodeIds: ['ep-oddlots-grid'],
      episodeCount: 1,
      ideas: [
        {
          idea: 'Own firm-power and grid-equipment names, not the chipmakers',
          proponent: 'Brian Janous',
          thesis: [`Power is the **binding constraint** on the buildout`, `Transformer and transmission supply is sold out for years`],
          kind: 'stock',
          episodeId: 'ep-oddlots-grid',
        },
        {
          idea: 'Buy already-permitted sites with signed interconnection agreements',
          proponent: 'Brian Janous',
          thesis: [`An interconnection agreement is a call option on the AI buildout`, `The public interconnection queue can take a decade`],
          kind: 'trade',
          episodeId: 'ep-oddlots-grid',
        },
      ],
      takeaways: [
        { title: 'Power, not chips, is the binding constraint', detail: `Electricity, interconnection queues, and transformer lead times — not silicon — gate the buildout.` },
      ],
      questions: [`Which permitted-site / interconnection owners are mispriced today?`],
    },
    {
      show: 'Stratechery',
      podcastId: 'stratechery',
      episodeIds: ['ep-stratechery-agg'],
      episodeCount: 1,
      ideas: [],
      takeaways: [{ title: 'Models are commoditizing', detail: `Durable value accrues to whoever owns distribution, not whoever owns the frontier model.` }],
      questions: [`Is "distribution beats models" already priced into the incumbents?`],
    },
    {
      show: 'Invest Like the Best',
      podcastId: 'iltb',
      episodeIds: ['ep-iltb-compounders'],
      episodeCount: 1,
      ideas: [],
      takeaways: [{ title: 'Permanent capital turns time into alpha', detail: `Owning the right business for a very long time — and staying liquid when others are forced sellers — is the edge.` }],
      questions: [],
    },
    {
      show: 'Acquired',
      podcastId: 'acquired',
      episodeIds: ['ep-acquired-tsmc'],
      episodeCount: 1,
      ideas: [],
      takeaways: [{ title: 'Concentration risk is structural', detail: `TSMC is a single-point-of-failure for the entire AI economy that reshoring won't fix quickly.` }],
      questions: [],
    },
  ],
  topThemes: [
    { label: 'Power & the grid', momentum: 64 },
    { label: 'AI capex: bubble or cycle', momentum: 41 },
    { label: 'Distribution > models', momentum: 33 },
    { label: 'Permanent capital', momentum: 18 },
    { label: 'Semiconductors', momentum: 12 },
  ],
  interesting: {
    title: 'Power, not chips, is the binding constraint',
    quote: `Forget the chips — you cannot pay your way to the front of an interconnection queue. The electrons don't care how much capital you've raised.`,
    speaker: 'Brian Janous',
    role: 'on Odd Lots',
    episodeId: 'ep-oddlots-grid',
  },
  takeaways: [
    { title: 'Power is the real AI constraint', detail: `Multiple shows converged on electricity, not silicon, as the binding limit on the buildout — with 2,000-day interconnection queues as the headline number.` },
    { title: 'Models are commoditizing', detail: `The week's contrarian-but-spreading view: durable value accrues to whoever owns distribution, not whoever owns the frontier model.` },
    { title: 'The IPO window cracked open', detail: `Reopening public markets reset venture math and pulled distributions forward for the first time in two years.` },
    { title: 'Concentration risk is structural', detail: `TSMC's dominance is a single-point-of-failure for the entire AI economy that reshoring won't fix quickly.` },
  ],
  contradictions: [
    `All-In's panel split hard on whether AI capex is a rational supercycle (Sacks) or a depreciation-driven bubble (Friedberg) — same data, opposite conclusions.`,
    `Stratechery says owning the model is a weak position; the AI Daily Brief framed frontier-model ownership as the enterprise kingmaker. Worth holding both.`,
  ],
  mentions: {
    people: ['Sam Altman', 'Morris Chang', 'Brian Janous', 'Satya Nadella', 'Nicolai Tangen'],
    companies: ['Nvidia', 'TSMC', 'Microsoft', 'OpenAI', 'Constellation Energy', 'Stripe'],
  },
  questions: [
    `If power is the constraint, which permitted-site / interconnection owners are mispriced today?`,
    `What depreciation schedule are hyperscalers actually using for GPUs — and what happens to margins if it's too aggressive?`,
    `Is "distribution beats models" already priced into the incumbents, or is there still a trade?`,
  ],
  sourceEpisodeIds: [
    'ep-oddlots-grid',
    'ep-stratechery-agg',
    'ep-allin-e184',
    'ep-iltb-compounders',
    'ep-acquired-tsmc',
  ],
}
