import type { jsPDF as JsPdf } from 'jspdf'
import type { Episode, Idea, Podcast, WeeklyIdea, WeeklySummary } from './types'
import { formatDuration, longDate } from './format'
import { sanitizeFilename } from './exportDoc'
import { weeklyReportBaseName } from './reportName'
import { COVER_BG } from './coverBg'
import { groupQuantByEpisode } from './weeklyQuant'

// ─────────────────────────────────────────────────────────────────────────────
// PDF export — a REAL .pdf, generated by a library (jsPDF), downloaded as a Blob.
//
// Why not the browser's print → Save-as-PDF? Because the app runs inside the
// chat.muns.io dashboard iframe, sandboxed WITHOUT `allow-modals`, so any
// script-initiated window.print() is a silent no-op. So we build the document
// ourselves — exactly like the Word `.doc` export does — and hand the user a
// finished file via `allow-downloads` (which always works in that sandbox).
//
// The whole house style is drawn as vector: the dark gradient cover (painted to
// an offscreen canvas, embedded as the cover image), gold section rules, the
// drop-cap lead, diamond-bullet idea cards, the dark quote panel, and the zebra
// source table. Text is real, selectable text. Fonts follow the same serif/sans/
// mono split the .doc uses (Times / Helvetica / Courier ≈ Georgia / Calibri /
// Consolas) — the three standard PDF families, so nothing needs embedding.
//
// Colours: navy #1a2b4a · gold #b8902f. **bold** prose renders in dark navy for
// readability (gold prose is too low-contrast on white, especially for long runs);
// gold is reserved for structure — section numbers, rules, subheads, bullet
// markers, [n] citation markers, badges — and for bold text on the dark quote panel.
// ─────────────────────────────────────────────────────────────────────────────

type RGB = [number, number, number]
type ById<T> = (id: string) => T | undefined

const A4 = { w: 595.28, h: 841.89 } // points
const A4L = { w: A4.h, h: A4.w } // landscape A4 — the fold-out for the wide Investment Readout table
const M = { l: 46, r: 46, t: 46, b: 48 }
const CW = A4.w - M.l - M.r
const LWC = A4L.w - M.l - M.r // landscape content width

// Each readout sits under its own episode, so the inline [n] citation markers are
// redundant noise in the table/cards — strip them for display.
const stripCites = (s: string): string => s.replace(/\s*\[\d+\]/g, '').replace(/\s{2,}/g, ' ').trim()

const C: Record<string, RGB> = {
  navy: [26, 43, 74],
  ink: [10, 19, 34],
  ink2: [43, 56, 80], // lead body #2b3850
  body: [65, 80, 106], // #41506a
  gold: [184, 144, 47],
  goldB: [206, 163, 68],
  goldDim: [150, 121, 52], // dim gold for hairline borders on light
  goldPale: [231, 207, 147],
  goldTint: [250, 246, 234],
  slate: [84, 96, 110],
  panel: [246, 248, 251],
  panel2: [238, 242, 247],
  line: [230, 234, 241],
  line2: [212, 219, 230],
  white: [255, 255, 255],
  zebra: [250, 251, 253],
  quoteBg: [19, 34, 58],
  coverTitle: [244, 238, 223],
  coverBrand: [243, 246, 251],
  coverFoot: [159, 176, 198],
}

const KIND_LABEL: Record<NonNullable<Idea['kind']>, string> = {
  stock: 'Stock',
  trade: 'Trade',
  macro: 'Macro',
  prediction: 'Prediction',
}

// ── Content model (pure, testable) ───────────────────────────────────────────
// Each block maps to one renderer. Sections are emitted only when they have a
// body (mirrors the .doc, which drops empty sections).
type Token = { w: string; b: boolean; c?: RGB; cite?: boolean; glue?: boolean }

// Closing punctuation that must hug the preceding word with NO leading space —
// the fix for "**buildout**: text" → "buildout: text" and "fiction [3] ." → "[3].",
// which the word-token wrapper would otherwise space apart at a bold/citation seam.
const GLUE_PUNCT = /^[.,:;!?%)\]}…»”’]/

/** A generic table column: header label, fractional width (of CW), alignment. */
export type Col = { header: string; w: number; align?: 'left' | 'right' }

export type Block =
  | { k: 'cover'; eyebrow?: string; kicker: string; title: string; dateRange?: string; chips: string[]; footerLeft: string }
  | { k: 'toc'; rows: { num: string; title: string }[] }
  | { k: 'section'; num: string; title: string }
  | { k: 'lead'; paras: string[] }
  | { k: 'showHead'; name: string; count: number }
  | { k: 'subhead'; label: string }
  | { k: 'idea'; kind?: string; title: string; who?: string; thesis: string[] }
  | { k: 'insight'; whatChanged?: string; whyItMatters?: string; beneficiaries: { name: string; why: string }[]; atRisk: { name: string; why: string }[]; diligence: string[] }
  | { k: 'takeaways'; items: { title: string; detail: string }[] }
  | { k: 'questions'; items: string[] }
  | { k: 'themes'; items: string[] }
  | { k: 'mentions'; people: string[]; companies: string[] }
  | { k: 'quote'; title?: string; quote: string; speaker: string; role: string }
  | { k: 'moment'; ts: string; star: boolean; title: string; detail: string }
  | { k: 'qa'; q: string; a: string }
  | { k: 'table'; cols: Col[]; rows: string[][] }
  | { k: 'note'; text: string }
  | { k: 'readoutTable'; cols: Col[]; rows: string[][] }
  | { k: 'readoutCard'; episode: string; theme: string; confidence: string; namesSectors: string; evidence: string; interpretation: string; questionsToVerify: string[]; action: string }
  | { k: 'sources'; rows: { episode: string; show: string }[] }
  | { k: 'footer'; left: string; right: string }

// Parse `**bold**` into word tokens carrying a bold flag (the unit the wrapper
// lays out). Inline `[n]` citation markers become their own gold tokens.
// Whitespace is normalised to single spaces.
export function runs(s: string): Token[] {
  const out: Token[] = []
  const push = (text: string, b: boolean) => {
    for (const w of text.split(/\s+/)) {
      if (!w) continue
      // Split a word on any [n] markers so each marker is its own (gold) token,
      // e.g. "measurement[1]" → "measurement" + "[1]".
      for (const part of w.split(/(\[\d+\])/)) {
        if (!part) continue
        if (/^\[\d+\]$/.test(part)) out.push({ w: part, b, cite: true })
        // A token that starts with closing punctuation glues to the previous word.
        else out.push({ w: part, b, ...(GLUE_PUNCT.test(part) ? { glue: true } : {}) })
      }
    }
  }
  const re = /\*\*([^*]+)\*\*/g
  let last = 0
  let m: RegExpExecArray | null
  while ((m = re.exec(s))) {
    push(s.slice(last, m.index), false)
    push(m[1], true)
    last = re.lastIndex
  }
  push(s.slice(last), false)
  return out
}

function ideaBlock(i: WeeklyIdea | Idea): Extract<Block, { k: 'idea' }> {
  return {
    k: 'idea',
    kind: i.kind ? KIND_LABEL[i.kind] : undefined,
    title: i.idea,
    who: i.proponent && i.proponent !== '—' ? i.proponent : undefined,
    thesis: i.thesis ?? [],
  }
}

const FOOTER_LEFT = 'Generated by Munshot · AI podcast intelligence'
// Every "back to Munshot" affordance in the PDF (cover wordmark, cover CTA, and
// the running page footers) is a live hyperlink to the dashboard.
const DASH_URL = 'https://chat.muns.io/dashboards?category=all&expanded=103'
const CTA_LABEL = 'Open the live dashboard'

// Section blocks accumulate into `body`; each `sec()` auto-numbers and is logged
// for the table of contents. The doc is assembled as [cover, toc, ...body], so the
// TOC lists exactly the sections that were emitted (empty ones are dropped).
function sectioned(make: (sec: (title: string) => void, body: Block[]) => void): { body: Block[]; toc: Extract<Block, { k: 'toc' }> } {
  const body: Block[] = []
  let n = 0
  const sec = (title: string) => {
    n += 1
    body.push({ k: 'section', num: String(n).padStart(2, '0'), title })
  }
  make(sec, body)
  const rows = body.filter((x): x is Extract<Block, { k: 'section' }> => x.k === 'section').map((x) => ({ num: x.num, title: x.title }))
  return { body, toc: { k: 'toc', rows } }
}

export function weeklyBlocks(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): Block[] {
  const eps = (n: number) => `${n} episode${n === 1 ? '' : 's'}`
  const cover: Block = {
    k: 'cover',
    eyebrow: 'AI Podcast Intelligence',
    kicker: 'Weekly Intelligence',
    title: 'Weekly Summary',
    dateRange: weekly.rangeLabel,
    chips: [eps(weekly.episodeCount), `${weekly.readMinutes} min read`],
    footerLeft: FOOTER_LEFT,
  }

  const keyThemes = weekly.keyThemes ?? []
  const quant = weekly.quantTable ?? []
  const readouts = weekly.episodeReadouts ?? []
  const shows = weekly.shows ?? []

  const { body, toc } = sectioned((sec, b) => {
    if (weekly.overview.length) {
      sec('Overview')
      b.push({ k: 'lead', paras: weekly.overview })
    }

    // Key Points — the synthesised, claim-first, cross-episode body (primary).
    if (keyThemes.length) {
      sec('Key Points')
      for (const t of keyThemes) {
        b.push({ k: 'subhead', label: t.heading })
        b.push({ k: 'takeaways', items: t.points.map((p) => ({ title: '', detail: p })) })
      }
    }

    if (quant.length) {
      sec('Quantitative Summary')
      // Grouped by episode so each number is clearly attributed to its source.
      const cols = [{ header: 'Metric', w: 0.34 }, { header: 'Value', w: 0.22, align: 'right' as const }, { header: 'Context', w: 0.44 }]
      for (const g of groupQuantByEpisode(quant, weekly.citations ?? [])) {
        if (g.label) b.push({ k: 'subhead', label: g.label })
        b.push({ k: 'table', cols, rows: g.rows.map((q) => [q.metric, q.value, q.context]) })
      }
    }

    if (readouts.length) {
      sec('Investment Readout')
      b.push({
        k: 'note',
        text: 'One readout per episode — what the podcast **actually said**, kept strictly separate from the investment **interpretation**, with the external checks to run next. The wide summary table is on the next (landscape) page; the per-episode detail follows it.',
      })
      b.push({
        k: 'readoutTable',
        cols: [
          { header: 'Episode', w: 0.1 },
          { header: 'Investable Theme', w: 0.15 },
          { header: 'Podcast Evidence', w: 0.2 },
          { header: 'Investment Interpretation', w: 0.2 },
          { header: 'Names / Sectors', w: 0.12 },
          { header: 'Confidence', w: 0.1 },
          { header: 'Action', w: 0.13 },
        ],
        rows: readouts.map((r) => [r.episode, stripCites(r.theme), stripCites(r.evidence), stripCites(r.interpretation), r.namesSectors, r.confidence, stripCites(r.action)]),
      })
      for (const r of readouts) {
        b.push({
          k: 'readoutCard',
          episode: r.episode,
          theme: stripCites(r.theme),
          confidence: r.confidence,
          namesSectors: r.namesSectors,
          evidence: stripCites(r.evidence),
          interpretation: stripCites(r.interpretation),
          questionsToVerify: r.questionsToVerify.map(stripCites),
          action: stripCites(r.action),
        })
      }
    }

    // Concrete calls — flattened across shows (kept out of the fragmented by-show
    // view when the synthesised Key Points are present).
    const ideas = shows.flatMap((s) => s.ideas)
    if (keyThemes.length && ideas.length) {
      sec('Ideas Pitched')
      for (const i of ideas) b.push(ideaBlock(i))
    }

    // By-show appendix — the no-AI fallback body (when no synthesised Key Points).
    if (!keyThemes.length && shows.length) {
      sec('By Show')
      for (const s of shows) {
        b.push({ k: 'showHead', name: s.show, count: s.episodeCount })
        if (s.ideas.length) {
          b.push({ k: 'subhead', label: 'Ideas Pitched' })
          for (const i of s.ideas) b.push(ideaBlock(i))
        }
        if (s.takeaways.length) {
          b.push({ k: 'subhead', label: 'Key Takeaways' })
          b.push({ k: 'takeaways', items: s.takeaways })
        }
        if (s.questions.length) {
          b.push({ k: 'subhead', label: 'Questions' })
          b.push({ k: 'questions', items: s.questions })
        }
      }
    }

    const rows = weekly.sourceEpisodeIds
      .map(episodeById)
      .filter((e): e is Episode => Boolean(e))
      .map((e) => ({ episode: e.title, show: podcastById(e.podcastId)?.title ?? '' }))
    if (rows.length) {
      sec('Sources')
      b.push({ k: 'sources', rows })
    }
  })

  return [cover, toc, ...body]
}

export function episodeBlocks(episode: Episode, podcast?: Podcast): Block[] {
  const s = episode.summary
  const cover: Block = {
    k: 'cover',
    eyebrow: podcast ? `${podcast.title} · ${podcast.author}` : 'Episode Intelligence',
    kicker: 'Episode Intelligence',
    title: episode.title,
    dateRange: longDate(episode.publishedAt),
    chips: [formatDuration(episode.durationSec), ...(s ? [`${s.highlights.length} highlights`, `${s.qa.length} questions`] : [])],
    footerLeft: FOOTER_LEFT,
  }

  const { body, toc } = sectioned((sec, b) => {
    if (s?.synthesis.length) {
      sec('AI Summary')
      b.push({ k: 'lead', paras: s.synthesis })
    }
    if (s?.insight) {
      sec('Investable Insight')
      b.push({
        k: 'insight',
        whatChanged: s.insight.whatChanged || undefined,
        whyItMatters: s.insight.whyItMatters || undefined,
        beneficiaries: s.insight.beneficiaries,
        atRisk: s.insight.atRisk,
        diligence: s.insight.diligenceQuestions,
      })
    }
    if (s?.quantData?.length) {
      sec('Key Numbers')
      b.push({
        k: 'table',
        cols: [{ header: 'Metric', w: 0.4 }, { header: 'Value', w: 0.24, align: 'right' }, { header: 'Context', w: 0.36 }],
        rows: s.quantData.map((q) => [q.metric, q.value, q.context]),
      })
    }
    if (s?.ideas?.length) {
      sec('Ideas Pitched')
      for (const i of s.ideas) b.push(ideaBlock(i))
    }
    if (s?.highlights.length) {
      sec('Highlights')
      for (const h of s.highlights) b.push({ k: 'moment', ts: h.timestamp, star: !!h.key, title: h.title, detail: h.detail })
    }
    if (s?.qa.length) {
      sec('Q&A')
      for (const item of s.qa) b.push({ k: 'qa', q: item.q, a: item.a })
    }
  })

  return [cover, toc, ...body]
}

// ── The painter: cursor + pagination + drawing ───────────────────────────────
type Fam = 'times' | 'helvetica' | 'courier'
interface RichOpts {
  sz: number
  lh: number
  fam: Fam
  color: RGB
  boldColor: RGB
  italic?: boolean
  indentFirst?: number
  indentLines?: number // how many leading lines get `indentFirst` (default 1) — drop caps indent 2
  noBreak?: boolean // caller has reserved the height; don't page-break mid-block
  align?: 'left' | 'right' // right-align each line within maxW (table number cells)
}

export class Painter {
  readonly d: JsPdf
  private readonly logo?: string
  /** Pass-2 render: section title → page number, so the TOC can print real pages. */
  private readonly pageMap?: Map<string, number>
  /** Pass-1 (probe) render: records each section's start page for the TOC. */
  private readonly record?: Map<string, number>
  /** Page numbers rendered in landscape (the readout fold-out) — the footer pass skips them. */
  readonly landscapePages = new Set<number>()
  y = M.t

  constructor(doc: JsPdf, logo?: string, opts: { pageMap?: Map<string, number>; record?: Map<string, number> } = {}) {
    this.d = doc
    this.pageMap = opts.pageMap
    this.record = opts.record
    this.logo = logo
  }

  private font(fam: Fam, style: string) {
    this.d.setFont(fam, style)
  }
  private color(c: RGB) {
    this.d.setTextColor(c[0], c[1], c[2])
  }
  private fill(c: RGB) {
    this.d.setFillColor(c[0], c[1], c[2])
  }
  private stroke(c: RGB, w = 0.5) {
    this.d.setDrawColor(c[0], c[1], c[2])
    this.d.setLineWidth(w)
  }
  private at(s: string, x: number, y = this.y) {
    this.d.text(s, x, y, { baseline: 'top' })
  }
  // jsPDF's getTextWidth ignores letter-spacing (the PDF Tc operator), so any
  // label drawn under setCharSpace measures short by `cs` per inter-glyph gap.
  // Add it back so pill badges contain their text and right/centre-aligned
  // letterspaced labels land where they should instead of overhanging.
  private spacedW(s: string, cs: number) {
    return this.d.getTextWidth(s) + cs * Math.max(0, s.length - 1)
  }
  // Attach a clickable hyperlink over a rectangle (top-left origin, matching the
  // baseline:'top' text the rect sits on). jsPDF flips y to PDF space internally.
  private link(x: number, y: number, w: number, h: number, url = DASH_URL) {
    this.d.link(x, y, w, h, { url })
  }
  private ensure(h: number) {
    if (this.y + h > A4.h - M.b) {
      this.d.addPage()
      this.y = M.t
    }
  }
  private diamond(cx: number, cy: number, r: number) {
    this.d.triangle(cx - r, cy, cx, cy - r, cx + r, cy, 'F')
    this.d.triangle(cx - r, cy, cx, cy + r, cx + r, cy, 'F')
  }

  // Lay out `**bold**`-aware tokens with word wrap. When draw=false, measures
  // only (returns the line count); when draw=true, paints and advances y.
  private rich(tokens: Token[], x: number, maxW: number, o: RichOpts, draw: boolean): number {
    const style = (b: boolean) => (o.italic ? (b ? 'bolditalic' : 'italic') : b ? 'bold' : 'normal')
    // Citation markers ([n]) render a touch smaller — set the right size per token.
    const sizeOf = (t: Token) => (t.cite ? o.sz * 0.82 : o.sz)
    const setFont = (t: Token) => {
      this.font(o.fam, style(t.b))
      this.d.setFontSize(sizeOf(t))
    }
    this.font(o.fam, 'normal')
    this.d.setFontSize(o.sz)
    const spaceW = this.d.getTextWidth(' ')

    // A leading indent (e.g. the cap recess of a drop-cap lead) can span the
    // first `indentLines` wrapped lines, not just the first one.
    const indentN = o.indentFirst ? o.indentLines ?? 1 : 0
    const indentFor = (li: number) => (li < indentN ? o.indentFirst ?? 0 : 0)

    const lines: (Token & { ww: number })[][] = []
    let cur: (Token & { ww: number })[] = []
    let cx = indentFor(0)
    for (const t of tokens) {
      setFont(t)
      const ww = this.d.getTextWidth(t.w)
      // A glued (closing-punctuation) token takes no leading space.
      const sp = cur.length && !t.glue ? spaceW : 0
      if (cur.length && cx + sp + ww > maxW) {
        lines.push(cur)
        cur = []
        cx = indentFor(lines.length)
        cur.push({ ...t, ww })
        cx += ww
        continue
      }
      cx += sp
      cur.push({ ...t, ww })
      cx += ww
    }
    if (cur.length || !lines.length) lines.push(cur)

    if (!draw) return lines.length
    for (let li = 0; li < lines.length; li++) {
      if (!o.noBreak) this.ensure(o.lh)
      const indent = indentFor(li)
      // Right-align: shift the whole line so its right edge meets x+maxW.
      let lx = x + indent
      if (o.align === 'right') {
        const lineW = lines[li].reduce((a, t, i) => a + t.ww + (i && !t.glue ? spaceW : 0), 0)
        lx = x + Math.max(0, maxW - lineW)
      }
      let first = true
      for (const t of lines[li]) {
        if (!first && !t.glue) lx += spaceW
        setFont(t)
        this.color(t.c ?? (t.cite ? C.gold : t.b ? o.boldColor : o.color))
        // Raise the smaller citation marker so it sits like a superscript.
        this.at(t.w, lx, t.cite ? this.y - 1.5 : this.y)
        lx += t.ww
        first = false
      }
      this.y += o.lh
    }
    return lines.length
  }

  // ── cover (full-bleed, its own page) ──
  cover(b: Extract<Block, { k: 'cover' }>) {
    const bg = makeCoverBg()
    if (bg) this.d.addImage(bg, 'JPEG', 0, 0, A4.w, A4.h)
    else {
      this.fill(C.ink)
      this.d.rect(0, 0, A4.w, A4.h, 'F')
    }

    const fi = 31 // frame inset
    this.stroke([150, 121, 52], 0.8)
    this.d.rect(fi, fi, A4.w - 2 * fi, A4.h - 2 * fi)

    const inX = fi + 30
    const inR = A4.w - fi - 30
    let cy = fi + 30
    if (this.logo) this.d.addImage(this.logo, 'PNG', inX, cy - 2, 24, 24)
    this.font('times', 'bold')
    this.d.setFontSize(15)
    this.color(C.coverBrand)
    const brandX = inX + (this.logo ? 32 : 0)
    this.at('Munshot', brandX, cy + 4)
    // The masthead (logo + wordmark) links back to the live dashboard.
    this.link(inX, cy - 2, brandX - inX + this.d.getTextWidth('Munshot'), 24)
    this.font('helvetica', 'bold')
    this.d.setFontSize(8)
    this.color(C.goldPale)
    this.d.setCharSpace(1.6)
    const kick = b.kicker.toUpperCase()
    this.at(kick, inR - this.spacedW(kick, 1.6), cy + 7)
    this.d.setCharSpace(0)

    cy += 40
    this.stroke([150, 121, 52], 0.8)
    this.d.line(inX, cy, inR, cy)

    // hero
    const heroTop = A4.h * 0.3
    let ty = heroTop
    if (this.logo) {
      const ls = 118
      this.d.addImage(this.logo, 'PNG', (A4.w - ls) / 2, heroTop, ls, ls)
      ty = heroTop + ls + 22
    }
    if (b.eyebrow) {
      this.font('helvetica', 'bold')
      this.d.setFontSize(8.5)
      this.color(C.goldB)
      this.d.setCharSpace(2.2)
      const e = b.eyebrow.toUpperCase()
      this.at(e, (A4.w - this.spacedW(e, 2.2)) / 2, ty)
      this.d.setCharSpace(0)
      ty += 20
    }
    // title — size shrinks for long episode titles
    const tsize = b.title.length > 60 ? 26 : b.title.length > 30 ? 34 : 50
    this.font('times', 'bold')
    this.d.setFontSize(tsize)
    this.color(C.coverTitle)
    const tlines = this.d.splitTextToSize(b.title, A4.w - 2 * (fi + 22)) as string[]
    for (const ln of tlines) {
      this.at(ln, (A4.w - this.d.getTextWidth(ln)) / 2, ty)
      ty += tsize * 1.04
    }
    ty += 8
    if (b.dateRange) {
      this.font('times', 'italic')
      this.d.setFontSize(17)
      this.color(C.goldPale)
      this.at(b.dateRange, (A4.w - this.d.getTextWidth(b.dateRange)) / 2, ty)
      ty += 26
    }
    if (b.chips.length) {
      this.font('courier', 'normal')
      this.d.setFontSize(7.6)
      this.d.setCharSpace(1)
      const pad = 11
      const gap = 10
      const ch = 17
      const labels = b.chips.map((c) => c.toUpperCase())
      const widths = labels.map((l) => this.spacedW(l, 1) + pad * 2)
      const total = widths.reduce((a, w) => a + w, 0) + gap * (labels.length - 1)
      let cx2 = (A4.w - total) / 2
      this.stroke([150, 121, 52], 0.6)
      for (let i = 0; i < labels.length; i++) {
        this.d.roundedRect(cx2, ty, widths[i], ch, 8, 8, 'S')
        this.color([205, 215, 230])
        this.at(labels[i], cx2 + pad, ty + 5)
        cx2 += widths[i] + gap
      }
      this.d.setCharSpace(0)
    }

    // Primary CTA — a filled-gold pill that links straight to the live dashboard.
    this.coverCta(ty + (b.chips.length ? 40 : 12))

    // footer
    const by = A4.h - fi - 38
    this.stroke([150, 121, 52], 0.8)
    this.d.line(inX, by, inR, by)
    this.font('helvetica', 'normal')
    this.d.setFontSize(8)
    this.color(C.coverFoot)
    this.at(stripMd(b.footerLeft), inX, by + 10)
    this.link(inX, by + 8, this.d.getTextWidth(stripMd(b.footerLeft)), 12)
    if (b.dateRange) {
      this.font('courier', 'normal')
      this.d.setFontSize(7.4)
      this.color(C.goldPale)
      this.d.setCharSpace(1.2)
      const r = b.dateRange.toUpperCase()
      this.at(r, inR - this.spacedW(r, 1.2), by + 10)
      this.d.setCharSpace(0)
    }
  }

  // Cover call-to-action — a filled-gold pill, centred, linking to the dashboard.
  // The vector go-triangle avoids any standard-font glyph-encoding surprises.
  private coverCta(top: number) {
    const h = 21
    const padX = 17
    const cs = 1.3
    const triGap = 9
    const triW = 5
    this.font('helvetica', 'bold')
    this.d.setFontSize(8.4)
    const label = CTA_LABEL.toUpperCase()
    const labelW = this.spacedW(label, cs)
    const w = padX + labelW + triGap + triW + padX
    const x = (A4.w - w) / 2
    this.fill(C.gold)
    this.d.roundedRect(x, top, w, h, h / 2, h / 2, 'F')
    this.color(C.ink)
    this.d.setCharSpace(cs)
    this.at(label, x + padX, top + 7.2)
    this.d.setCharSpace(0)
    const ax = x + padX + labelW + triGap
    const ay = top + h / 2
    this.fill(C.ink)
    this.d.triangle(ax, ay - 3.1, ax, ay + 3.1, ax + triW, ay, 'F')
    this.link(x, top, w, h)
  }

  sectionHead(num: string, title: string) {
    this.ensure(34)
    // Record which page this section lands on (probe pass) so the TOC can print it.
    if (this.record) this.record.set(title, this.d.getNumberOfPages())
    this.y += 6
    this.font('times', 'bold')
    this.d.setFontSize(23)
    this.color(C.gold)
    this.at(num, M.l, this.y)
    const nw = this.d.getTextWidth(num)
    this.font('times', 'bold')
    this.d.setFontSize(15.5)
    this.color(C.navy)
    this.at(title, M.l + nw + 12, this.y + 7)
    const tw = this.d.getTextWidth(title)
    const rx = M.l + nw + 12 + tw + 12
    this.stroke(C.gold, 0.8)
    if (rx < A4.w - M.r) this.d.line(rx, this.y + 16, A4.w - M.r, this.y + 16)
    this.y += 30
  }

  lead(paras: string[]) {
    const padX = 16
    const padT = 14
    const padB = 12
    const lh = 15
    const sz = 10.2
    const innerW = CW - 2 * padX
    // A true two-line drop cap: a Times-bold initial sized to span the first two
    // body lines, with those two lines recessed to its right. Sizing it to ~2 lh
    // lands the cap's baseline on the second line and its top on the first, so it
    // no longer overhangs the (un-indented) third line the way a 1-line cap did.
    const capLines = 2
    const capSize = 33
    const capGap = 5
    const first = paras[0] || ''
    const cap = first.charAt(0)
    this.font('times', 'bold')
    this.d.setFontSize(capSize)
    const indentW = this.d.getTextWidth(cap) + capGap
    const firstRest = runs(first.slice(1))
    const leadOpt: RichOpts = { sz, lh, fam: 'helvetica', color: C.ink2, boldColor: C.navy, indentFirst: indentW, indentLines: capLines, noBreak: true }
    const bodyOpt: RichOpts = { sz, lh, fam: 'helvetica', color: C.ink2, boldColor: C.navy, noBreak: true }

    // Measure. The first paragraph reserves at least `capLines` rows so a short
    // opener still leaves room for the cap before the next paragraph.
    const firstLines = Math.max(this.rich(firstRest, M.l + padX, innerW, leadOpt, false), capLines)
    let total = padT + firstLines * lh
    for (let i = 1; i < paras.length; i++) total += 8 + this.rich(runs(paras[i]), M.l + padX, innerW, bodyOpt, false) * lh
    total += padB

    this.ensure(total)
    const top = this.y
    this.fill(C.goldTint)
    this.d.rect(M.l, top, CW, total, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, total, 'F')

    const firstTop = top + padT
    this.y = firstTop
    this.rich(firstRest, M.l + padX, innerW, leadOpt, true)
    this.y = firstTop + firstLines * lh // clear the cap before the next paragraph
    for (let i = 1; i < paras.length; i++) {
      this.y += 8
      this.rich(runs(paras[i]), M.l + padX, innerW, bodyOpt, true)
    }
    // Cap drawn last, top-aligned with the first line's cap height.
    this.font('times', 'bold')
    this.d.setFontSize(capSize)
    this.color(C.gold)
    this.at(cap, M.l + padX, firstTop)
    this.y = top + total + 12
  }

  showHead(name: string, count: number) {
    this.ensure(26)
    this.y += 6
    this.font('times', 'bold')
    this.d.setFontSize(13.5)
    this.color(C.navy)
    this.at(name, M.l, this.y)
    const label = `${count} EPISODE${count === 1 ? '' : 'S'}`
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.2)
    this.d.setCharSpace(0.6)
    const w = this.spacedW(label, 0.6) + 16
    this.fill(C.goldTint)
    this.stroke([150, 121, 52], 0.5)
    this.d.roundedRect(M.l + CW - w, this.y - 1, w, 13, 6, 6, 'FD')
    this.color(C.gold)
    this.at(label, M.l + CW - w + 8, this.y + 2.5)
    this.d.setCharSpace(0)
    this.y += 18
    this.stroke(C.line2, 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 9
  }

  subhead(label: string) {
    this.ensure(20)
    this.y += 4
    this.fill(C.gold)
    this.d.rect(M.l, this.y + 3, 12, 2, 'F')
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.8)
    this.color(C.gold)
    this.d.setCharSpace(1.4)
    this.at(label.toUpperCase(), M.l + 18, this.y)
    this.d.setCharSpace(0)
    this.y += 15
  }

  idea(b: Extract<Block, { k: 'idea' }>) {
    const padX = 12
    const padV = 9
    const innerW = CW - 2 * padX
    let kindW = 0
    if (b.kind) {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.8)
      kindW = this.d.getTextWidth(b.kind.toUpperCase()) + 12 + 7
    }
    const titleOpt: RichOpts = { sz: 11.4, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, indentFirst: kindW, noBreak: true }
    const thOpt: RichOpts = { sz: 9.2, lh: 12.5, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true }

    let h = padV + this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 14
    if (b.who) h += 5 + 16
    if (b.thesis.length) {
      h += 4
      for (const t of b.thesis) h += this.rich(runs(t), M.l + padX + 14, innerW - 14, thOpt, false) * 12.5 + 2
    }
    h += padV

    this.ensure(h)
    const top = this.y
    this.fill(C.panel)
    this.d.rect(M.l, top, CW, h, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, h, 'F')
    this.stroke(C.line, 0.5)
    this.d.rect(M.l, top, CW, h)

    this.y = top + padV
    if (b.kind) {
      const kl = b.kind.toUpperCase()
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.8)
      const w = this.d.getTextWidth(kl) + 12
      this.stroke([150, 121, 52], 0.5)
      this.d.roundedRect(M.l + padX, this.y, w, 11, 3, 3, 'S')
      this.color(C.gold)
      this.at(kl, M.l + padX + 6, this.y + 2.8)
    }
    this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
    if (b.who) {
      this.y += 5
      this.font('helvetica', 'normal')
      this.d.setFontSize(7.3)
      const pre = 'Pitched by '
      const w = this.d.getTextWidth(pre + b.who) + 18
      this.fill(C.white)
      this.stroke(C.line2, 0.5)
      this.d.roundedRect(M.l + padX, this.y, w, 14, 7, 7, 'FD')
      this.color(C.slate)
      this.at(pre, M.l + padX + 9, this.y + 3.5)
      const pw = this.d.getTextWidth(pre)
      this.font('helvetica', 'bold')
      this.color(C.navy)
      this.at(b.who, M.l + padX + 9 + pw, this.y + 3.5)
      this.y += 16
    }
    if (b.thesis.length) {
      this.y += 4
      for (const t of b.thesis) {
        this.fill(C.gold)
        this.diamond(M.l + padX + 3, this.y + 5, 2.4)
        this.rich(runs(t), M.l + padX + 14, innerW - 14, thOpt, true)
        this.y += 2
      }
    }
    this.y = top + h + 7
  }

  takeaways(items: { title: string; detail: string }[]) {
    const lh = 14
    for (const it of items) {
      const titleWords = it.title
        .split(/\s+/)
        .filter(Boolean)
        .map((w, i, a): Token => ({ w: i === a.length - 1 ? w + '.' : w, b: true, c: C.navy }))
      const toks = titleWords.concat(runs(it.detail))
      const opt: RichOpts = { sz: 10, lh, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true }
      const lines = this.rich(toks, M.l + 16, CW - 16, opt, false)
      this.ensure(lines * lh + 6)
      this.fill(C.gold)
      this.d.rect(M.l + 1, this.y + 5, 4, 4, 'F')
      this.rich(toks, M.l + 16, CW - 16, opt, true)
      this.y += 6
    }
  }

  questions(items: string[]) {
    const lh = 12.5
    for (const q of items) {
      const opt: RichOpts = { sz: 9, lh, fam: 'helvetica', italic: true, color: [70, 86, 111], boldColor: C.navy, noBreak: true }
      const lines = this.rich(runs(q), M.l + 14, CW - 14, opt, false)
      this.ensure(lines * lh + 6)
      this.fill(C.goldB)
      this.d.rect(M.l, this.y + 1, 2, lines * lh - 2, 'F')
      this.rich(runs(q), M.l + 14, CW - 14, opt, true)
      this.y += 6
    }
  }

  themes(items: string[]) {
    this.font('courier', 'normal')
    this.d.setFontSize(8)
    const pad = 10
    const gap = 7
    const ch = 16
    const lh = ch + 7
    let cx = M.l
    this.ensure(ch)
    for (const raw of items) {
      const label = raw.toUpperCase()
      const w = this.d.getTextWidth(label) + pad * 2
      if (cx > M.l && cx + w > M.l + CW) {
        this.y += lh
        cx = M.l
        this.ensure(ch)
      }
      this.fill(C.goldTint)
      this.stroke([150, 121, 52], 0.5)
      this.d.roundedRect(cx, this.y, w, ch, 8, 8, 'FD')
      this.color(C.navy)
      this.at(label, cx + pad, this.y + 4.5)
      cx += w + gap
    }
    this.y += ch + 8
  }

  mentions(people: string[], companies: string[]) {
    const groups: [string, string[]][] = [
      ['People', people],
      ['Companies', companies],
    ]
    for (const [label, items] of groups) {
      if (!items.length) continue
      this.ensure(24)
      this.y += 2
      this.font('helvetica', 'bold')
      this.d.setFontSize(8)
      this.color(C.navy)
      this.d.setCharSpace(1.4)
      this.at(label.toUpperCase(), M.l, this.y)
      this.d.setCharSpace(0)
      this.y += 11
      this.stroke(C.gold, 1.2)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      this.y += 8
      // chips
      this.font('helvetica', 'bold')
      this.d.setFontSize(8)
      const pad = 10
      const gap = 5
      const ch = 15
      const lh = ch + 5
      let cx = M.l
      this.ensure(ch)
      for (const it of items) {
        const w = this.d.getTextWidth(it) + pad * 2
        if (cx > M.l && cx + w > M.l + CW) {
          this.y += lh
          cx = M.l
          this.ensure(ch)
        }
        this.fill(C.panel2)
        this.stroke(C.line2, 0.5)
        this.d.roundedRect(cx, this.y, w, ch, 7, 7, 'FD')
        this.color(C.navy)
        this.at(it, cx + pad, this.y + 3.5)
        cx += w + gap
      }
      this.y += ch + 8
    }
  }

  quote(b: Extract<Block, { k: 'quote' }>) {
    const padX = 22
    const padV = 18
    const innerW = CW - 2 * padX
    const titleOpt: RichOpts = { sz: 15, lh: 18, fam: 'times', color: C.goldPale, boldColor: C.navyPale, noBreak: true }
    const qOpt: RichOpts = { sz: 12.4, lh: 17, fam: 'times', italic: true, color: [221, 230, 242], boldColor: C.navyPale, noBreak: true }

    let h = padV
    if (b.title) h += this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 18 + 8
    h += this.rich(runs(b.quote), M.l + padX, innerW, qOpt, false) * 17
    h += 14 + 12 + padV

    this.ensure(h)
    const top = this.y
    this.fill(C.quoteBg)
    this.d.roundedRect(M.l, top, CW, h, 12, 12, 'F')
    this.stroke([150, 121, 52], 0.6)
    this.d.roundedRect(M.l, top, CW, h, 12, 12, 'S')
    // oversized quote mark, faint gold
    this.font('times', 'bold')
    this.d.setFontSize(58)
    this.color(C.gold)
    this.d.setGState(this.d.GState({ opacity: 0.22 }))
    this.at('“', M.l + 10, top - 8)
    this.d.setGState(this.d.GState({ opacity: 1 }))

    this.y = top + padV
    if (b.title) {
      this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
      this.y += 8
    }
    this.rich(runs(b.quote), M.l + padX, innerW, qOpt, true)
    this.y += 12
    this.fill(C.goldB)
    this.diamond(M.l + padX + 3, this.y + 5, 2.4)
    this.font('helvetica', 'bold')
    this.d.setFontSize(8.4)
    this.color(C.goldB)
    this.at(b.speaker, M.l + padX + 12, this.y + 1.5)
    const sw = this.d.getTextWidth(b.speaker)
    this.font('helvetica', 'normal')
    this.d.setFontSize(8)
    this.color([159, 177, 200])
    this.at('  ' + b.role, M.l + padX + 12 + sw, this.y + 1.5)
    this.y = top + h + 12
  }

  moment(b: Extract<Block, { k: 'moment' }>) {
    const padX = 12
    const padV = 9
    const innerW = CW - 2 * padX
    this.font('courier', 'normal')
    this.d.setFontSize(7.4)
    const tsW = this.d.getTextWidth(b.ts) + 12
    let indent = tsW + 8
    if (b.star) indent += 12
    const titleOpt: RichOpts = { sz: 11.2, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, indentFirst: indent, noBreak: true }
    const whyOpt: RichOpts = { sz: 9.2, lh: 13, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true }

    let h = padV + this.rich(runs(b.title), M.l + padX, innerW, titleOpt, false) * 14
    h += 4 + this.rich(runs(b.detail), M.l + padX, innerW, whyOpt, false) * 13 + padV

    this.ensure(h)
    const top = this.y
    this.fill(C.panel)
    this.d.rect(M.l, top, CW, h, 'F')
    this.fill(C.gold)
    this.d.rect(M.l, top, 3, h, 'F')
    this.stroke(C.line, 0.5)
    this.d.rect(M.l, top, CW, h)

    this.y = top + padV
    this.fill(C.goldTint)
    this.stroke([150, 121, 52], 0.5)
    this.d.roundedRect(M.l + padX, this.y, tsW, 12, 4, 4, 'FD')
    this.font('courier', 'normal')
    this.d.setFontSize(7.4)
    this.color(C.gold)
    this.at(b.ts, M.l + padX + 6, this.y + 2.8)
    if (b.star) {
      this.fill(C.gold)
      this.diamond(M.l + padX + tsW + 8, this.y + 6, 3)
    }
    this.rich(runs(b.title), M.l + padX, innerW, titleOpt, true)
    this.y += 4
    this.rich(runs(b.detail), M.l + padX, innerW, whyOpt, true)
    this.y = top + h + 7
  }

  qa(b: Extract<Block, { k: 'qa' }>) {
    const qbW = 16
    const qOpt: RichOpts = { sz: 11.2, lh: 14, fam: 'times', color: C.navy, boldColor: C.navy, noBreak: true }
    const qLines = this.rich(runs(b.q), M.l + qbW + 8, CW - qbW - 8, qOpt, false)
    this.ensure(qLines * 14 + 20)
    this.y += 2
    this.fill(C.gold)
    this.d.roundedRect(M.l, this.y, qbW, 12, 2, 2, 'F')
    this.font('helvetica', 'bold')
    this.d.setFontSize(7.2)
    this.color(C.white)
    this.at('Q', M.l + (qbW - this.d.getTextWidth('Q')) / 2, this.y + 2.8)
    this.rich(runs(b.q), M.l + qbW + 8, CW - qbW - 8, qOpt, true)
    this.y += 4
    // answer is breakable (can run long)
    this.rich(runs(b.a), M.l, CW, { sz: 9.4, lh: 13.5, fam: 'helvetica', color: C.body, boldColor: C.navy }, true)
    this.y += 9
    this.stroke(C.line, 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 9
  }

  sources(rows: { episode: string; show: string }[]) {
    const palette: RGB[] = [C.navy, C.gold, C.slate]
    const colorMap = new Map<string, RGB>()
    let ci = 0
    const tagColor = (show: string): RGB => {
      let c = colorMap.get(show)
      if (!c) {
        c = palette[ci++ % palette.length]
        colorMap.set(show, c)
      }
      return c
    }
    const header = () => {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.9)
      this.color(C.gold)
      this.d.setCharSpace(1.4)
      this.at('EPISODE', M.l, this.y + 4)
      const sh = 'SHOW'
      this.at(sh, M.l + CW - this.spacedW(sh, 1.4), this.y + 4)
      this.d.setCharSpace(0)
      this.y += 14
      this.stroke(C.gold, 1.4)
      this.d.line(M.l, this.y, M.l + CW, this.y)
    }
    this.ensure(40)
    header()
    let zebra = false
    const epOpt: RichOpts = { sz: 9.1, lh: 12, fam: 'helvetica', color: C.navy, boldColor: C.navy, noBreak: true }
    const tagW = (show: string) => {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.9)
      return show ? this.spacedW(show.toUpperCase(), 0.4) + 16 : 0
    }
    for (const row of rows) {
      const lines = this.rich(runs(row.episode), M.l + 9, CW - 18 - tagW(row.show) - 10, epOpt, false)
      const rh = Math.max(lines * 12 + 11, 26)
      if (this.y + rh > A4.h - M.b) {
        this.d.addPage()
        this.y = M.t
        header()
      }
      const top = this.y
      if (zebra) {
        this.fill(C.zebra)
        this.d.rect(M.l, top, CW, rh, 'F')
      }
      this.y = top + 6
      this.rich(runs(row.episode), M.l + 9, CW - 18 - tagW(row.show) - 10, epOpt, true)
      if (row.show) {
        const t = row.show.toUpperCase()
        this.font('helvetica', 'bold')
        this.d.setFontSize(6.9)
        const w = this.spacedW(t, 0.4) + 16
        const x = M.l + CW - w - 6
        const yy = top + (rh - 13) / 2
        this.fill(tagColor(row.show))
        this.d.roundedRect(x, yy, w, 13, 3, 3, 'F')
        this.color(C.white)
        this.d.setCharSpace(0.4)
        this.at(t, x + 8, yy + 3)
        this.d.setCharSpace(0)
      }
      this.y = top + rh
      this.stroke(C.line, 0.5)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      zebra = !zebra
    }
    this.y += 4
  }

  footer(left: string, right: string) {
    this.ensure(32)
    this.y += 12
    this.stroke([216, 193, 135], 0.5)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 8
    this.font('helvetica', 'normal')
    this.d.setFontSize(7.6)
    this.color([136, 147, 162])
    this.at(stripMd(left), M.l, this.y)
    this.color(C.gold)
    this.d.setCharSpace(1)
    const r = right.toUpperCase()
    this.at(r, M.l + CW - this.spacedW(r, 1), this.y)
    this.d.setCharSpace(0)
  }

  // ── Table of contents — numbered rows, dotted leaders, right page numbers ────
  toc(rows: { num: string; title: string }[]) {
    this.y += 6
    this.font('times', 'bold')
    this.d.setFontSize(11)
    this.color(C.navy)
    this.d.setCharSpace(2)
    this.at('CONTENTS', M.l, this.y)
    this.d.setCharSpace(0)
    this.y += 10
    this.stroke(C.gold, 1.2)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 16

    const dotW = this.d.getTextWidth('.')
    for (const r of rows) {
      this.ensure(20)
      this.font('times', 'bold')
      this.d.setFontSize(10)
      this.color(C.gold)
      this.at(r.num, M.l, this.y)
      const numW = this.d.getTextWidth(r.num)
      this.color(C.navy)
      this.at(r.title, M.l + numW + 10, this.y)
      const titleEnd = M.l + numW + 10 + this.d.getTextWidth(r.title)

      const page = this.pageMap?.get(r.title)
      const pageStr = page != null ? String(page) : ''
      this.font('helvetica', 'normal')
      this.d.setFontSize(9)
      const pageW = pageStr ? this.d.getTextWidth(pageStr) : 0
      const pageX = M.l + CW - pageW
      // Dotted leader between the title and the page number.
      this.color(C.line2)
      const leaderStart = titleEnd + 6
      const leaderEnd = pageX - 6
      if (leaderEnd > leaderStart && dotW > 0) {
        const n = Math.floor((leaderEnd - leaderStart) / (dotW * 1.6))
        let dx = leaderStart
        for (let i = 0; i < n; i++) {
          this.at('.', dx, this.y + 1)
          dx += dotW * 1.6
        }
      }
      if (pageStr) {
        this.color(C.slate)
        this.at(pageStr, pageX, this.y)
      }
      this.y += 19
    }
    this.y += 6
  }

  // ── Generic table — header row + zebra body, wrapping cells, repeating header
  //    across page breaks. The basis for the Quant + Comparison tables. ─────────
  table(cols: Col[], rows: string[][]) {
    const pad = 8
    const totalW = cols.reduce((a, c) => a + c.w, 0) || 1
    const widths = cols.map((c) => (c.w / totalW) * CW)
    const xs: number[] = []
    let acc = M.l
    for (const w of widths) {
      xs.push(acc)
      acc += w
    }
    const cellOpt = (align?: 'left' | 'right'): RichOpts => ({ sz: 8.7, lh: 11.6, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true, align })
    const header = () => {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.9)
      this.color(C.gold)
      this.d.setCharSpace(1)
      cols.forEach((c, i) => {
        const label = c.header.toUpperCase()
        const lx = c.align === 'right' ? xs[i] + widths[i] - pad - this.spacedW(label, 1) : xs[i] + pad
        this.at(label, lx, this.y + 4)
      })
      this.d.setCharSpace(0)
      this.y += 15
      this.stroke(C.gold, 1.2)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      this.y += 3
    }
    this.ensure(48)
    header()
    let zebra = false
    for (const row of rows) {
      let maxLines = 1
      cols.forEach((c, i) => {
        const lines = this.rich(runs(row[i] ?? ''), xs[i] + pad, widths[i] - 2 * pad, cellOpt(c.align), false)
        if (lines > maxLines) maxLines = lines
      })
      const rh = maxLines * 11.6 + 9
      if (this.y + rh > A4.h - M.b) {
        this.d.addPage()
        this.y = M.t
        header()
      }
      const top = this.y
      if (zebra) {
        this.fill(C.zebra)
        this.d.rect(M.l, top, CW, rh, 'F')
      }
      cols.forEach((c, i) => {
        this.y = top + 5
        this.rich(runs(row[i] ?? ''), xs[i] + pad, widths[i] - 2 * pad, cellOpt(c.align), true)
      })
      this.y = top + rh
      this.stroke(C.line, 0.5)
      this.d.line(M.l, this.y, M.l + CW, this.y)
      zebra = !zebra
    }
    this.y += 6
  }

  // ── Investable-insight card — the per-episode five-part read ─────────────────
  insight(b: Extract<Block, { k: 'insight' }>) {
    const labelRow = (label: string) => {
      this.ensure(16)
      this.fill(C.gold)
      this.d.rect(M.l, this.y + 3, 10, 2, 'F')
      this.font('helvetica', 'bold')
      this.d.setFontSize(7.4)
      this.color(C.gold)
      this.d.setCharSpace(1.2)
      this.at(label.toUpperCase(), M.l + 16, this.y)
      this.d.setCharSpace(0)
      this.y += 13
    }
    const prose = (s: string) => {
      this.rich(runs(s), M.l, CW, { sz: 9.6, lh: 13.5, fam: 'helvetica', color: C.ink2, boldColor: C.navy }, true)
      this.y += 6
    }
    if (b.whatChanged) {
      labelRow('What changed')
      prose(b.whatChanged)
    }
    if (b.whyItMatters) {
      labelRow('Why it matters')
      prose(b.whyItMatters)
    }
    // Two-up Beneficiaries / At-risk — named parties with the mechanism.
    const party = (label: string, items: { name: string; why: string }[], dot: RGB) => {
      if (!items.length) return
      labelRow(label)
      for (const p of items) {
        const toks: Token[] = [{ w: p.name + (p.why ? ' —' : ''), b: true, c: C.navy }, ...runs(p.why)]
        const lines = this.rich(toks, M.l + 14, CW - 14, { sz: 9.2, lh: 12.5, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true }, false)
        this.ensure(lines * 12.5 + 4)
        this.fill(dot)
        this.diamond(M.l + 3, this.y + 5, 2.4)
        this.rich(toks, M.l + 14, CW - 14, { sz: 9.2, lh: 12.5, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true }, true)
        this.y += 3
      }
      this.y += 4
    }
    party('Who benefits', b.beneficiaries, [42, 122, 72])
    party("Who's at risk", b.atRisk, [168, 64, 64])
    if (b.diligence.length) {
      labelRow('Diligence questions')
      this.questions(b.diligence)
    }
    this.y += 2
  }

  // ── Investment Readout (weekly) — a plain intro paragraph, a landscape fold-out
  //    summary table, and the per-episode cards. ───────────────────────────────
  note(text: string) {
    this.ensure(16)
    this.rich(runs(text), M.l, CW, { sz: 9.4, lh: 14, fam: 'helvetica', color: C.ink2, boldColor: C.navy }, true)
    this.y += 8
  }

  // The wide 7-column summary, on its own landscape page(s). Adds the landscape
  // page(s) here and returns to a portrait page for the cards that follow.
  readoutTable(cols: Col[], rows: string[][]) {
    this.d.addPage('a4', 'landscape')
    this.landscapePages.add(this.d.getNumberOfPages())
    this.y = M.t
    this.font('times', 'bold')
    this.d.setFontSize(13)
    this.color(C.navy)
    this.at('Investment Readout — per-episode summary', M.l, this.y)
    this.y += 20
    const pad = 8
    const totalW = cols.reduce((a, c) => a + c.w, 0) || 1
    const widths = cols.map((c) => (c.w / totalW) * LWC)
    const xs: number[] = []
    let acc = M.l
    for (const w of widths) {
      xs.push(acc)
      acc += w
    }
    const cellOpt = (align?: 'left' | 'right'): RichOpts => ({ sz: 7.7, lh: 10.2, fam: 'helvetica', color: C.body, boldColor: C.navy, noBreak: true, align })
    const header = () => {
      this.font('helvetica', 'bold')
      this.d.setFontSize(6.6)
      this.color(C.gold)
      this.d.setCharSpace(0.8)
      cols.forEach((c, i) => {
        const label = c.header.toUpperCase()
        const lx = c.align === 'right' ? xs[i] + widths[i] - pad - this.spacedW(label, 0.8) : xs[i] + pad
        this.at(label, lx, this.y + 4)
      })
      this.d.setCharSpace(0)
      this.y += 14
      this.stroke(C.gold, 1.2)
      this.d.line(M.l, this.y, M.l + LWC, this.y)
      this.y += 3
    }
    header()
    let zebra = false
    for (const row of rows) {
      let maxLines = 1
      cols.forEach((c, i) => {
        const lines = this.rich(runs(row[i] ?? ''), xs[i] + pad, widths[i] - 2 * pad, cellOpt(c.align), false)
        if (lines > maxLines) maxLines = lines
      })
      const rh = maxLines * 10.2 + 8
      if (this.y + rh > A4L.h - M.b) {
        this.d.addPage('a4', 'landscape')
        this.landscapePages.add(this.d.getNumberOfPages())
        this.y = M.t
        header()
      }
      const top = this.y
      if (zebra) {
        this.fill(C.zebra)
        this.d.rect(M.l, top, LWC, rh, 'F')
      }
      cols.forEach((c, i) => {
        this.y = top + 5
        this.rich(runs(row[i] ?? ''), xs[i] + pad, widths[i] - 2 * pad, cellOpt(c.align), true)
      })
      this.y = top + rh
      this.stroke(C.line, 0.5)
      this.d.line(M.l, this.y, M.l + LWC, this.y)
      zebra = !zebra
    }
    this.d.addPage('a4', 'portrait')
    this.y = M.t
  }

  readoutCard(b: Extract<Block, { k: 'readoutCard' }>) {
    this.ensure(40)
    this.y += 4
    // Episode title + a confidence chip pinned to the right.
    this.font('times', 'bold')
    this.d.setFontSize(13)
    this.color(C.navy)
    this.at(b.episode, M.l, this.y)
    const lvl = b.confidence
    const cc: RGB = lvl === 'High' ? [42, 122, 72] : lvl === 'Low' ? C.slate : C.gold
    this.font('helvetica', 'bold')
    this.d.setFontSize(6.8)
    this.d.setCharSpace(0.6)
    const cl = `${lvl.toUpperCase()} CONFIDENCE`
    const cw = this.spacedW(cl, 0.6) + 14
    this.stroke(cc, 0.7)
    this.d.roundedRect(M.l + CW - cw, this.y - 1, cw, 12, 6, 6, 'S')
    this.color(cc)
    this.at(cl, M.l + CW - cw + 7, this.y + 2.5)
    this.d.setCharSpace(0)
    this.y += 16
    // Theme (gold).
    this.rich(runs(b.theme), M.l, CW, { sz: 10, lh: 13, fam: 'helvetica', color: C.gold, boldColor: C.gold }, true)
    if (b.namesSectors && b.namesSectors !== '—') {
      this.font('helvetica', 'normal')
      this.d.setFontSize(8)
      this.color(C.slate)
      this.at(b.namesSectors, M.l, this.y)
      this.y += 12
    }
    this.y += 3
    const labelRow = (label: string) => {
      this.ensure(16)
      this.fill(C.gold)
      this.d.rect(M.l, this.y + 3, 10, 2, 'F')
      this.font('helvetica', 'bold')
      this.d.setFontSize(7.4)
      this.color(C.gold)
      this.d.setCharSpace(1.2)
      this.at(label.toUpperCase(), M.l + 16, this.y)
      this.d.setCharSpace(0)
      this.y += 13
    }
    const prose = (s: string) => {
      this.rich(runs(s), M.l, CW, { sz: 9.4, lh: 13, fam: 'helvetica', color: C.ink2, boldColor: C.navy }, true)
      this.y += 5
    }
    labelRow('Podcast evidence')
    prose(b.evidence)
    labelRow('Investment interpretation')
    prose(b.interpretation)
    if (b.questionsToVerify.length) {
      labelRow('Questions to verify')
      this.questions(b.questionsToVerify)
    }
    if (b.action) {
      labelRow('Action')
      prose(b.action)
    }
    this.y += 4
    this.stroke(C.line, 0.6)
    this.d.line(M.l, this.y, M.l + CW, this.y)
    this.y += 8
  }
}

// Stamp a running footer on every page except the full-bleed cover (and the
// landscape readout fold-out pages, which have no room for it). Page numbers are
// only knowable after the whole document is laid out, hence a post-pass.
function stampFooters(doc: JsPdf, opts: { left: string; right: string; skip?: Set<number> }): void {
  const total = doc.getNumberOfPages()
  for (let i = 2; i <= total; i++) {
    if (opts.skip?.has(i)) continue
    doc.setPage(i)
    const y = A4.h - 30
    doc.setDrawColor(216, 193, 135)
    doc.setLineWidth(0.5)
    doc.line(M.l, y, M.l + CW, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.4)
    doc.setTextColor(136, 147, 162)
    const leftText = stripMd(opts.left)
    doc.text(leftText, M.l, y + 9, { baseline: 'top' })
    doc.link(M.l, y + 7, doc.getTextWidth(leftText), 12, { url: DASH_URL })
    const mid = 'Confidential'
    doc.text(mid, (A4.w - doc.getTextWidth(mid)) / 2, y + 9, { baseline: 'top' })
    doc.setTextColor(184, 144, 47)
    doc.setCharSpace(1)
    const right = `${opts.right.toUpperCase()}  ·  ${i} / ${total}`
    // getTextWidth ignores letter-spacing — add it back so the date doesn't overhang.
    const rightW = doc.getTextWidth(right) + 1 * Math.max(0, right.length - 1)
    doc.text(right, M.l + CW - rightW, y + 9, { baseline: 'top' })
    doc.setCharSpace(0)
  }
}

function stripMd(s: string): string {
  return s.replace(/\*\*/g, '')
}

// Paint the cover's layered gradients to a canvas and return a JPEG data URI, so
// the cover keeps the exact dark navy + gold-glow look (jsPDF has no gradients).
// Without a DOM (the server-side cron / hosted-report render, and tests) fall back
// to the baked gradient JPEG, so the emailed PDF cover matches the downloaded one.
function makeCoverBg(): string | null {
  if (typeof document === 'undefined') return COVER_BG
  try {
    const sc = 2
    const W = Math.round(A4.w * sc)
    const H = Math.round(A4.h * sc)
    const canvas = document.createElement('canvas')
    canvas.width = W
    canvas.height = H
    const x = canvas.getContext('2d')
    if (!x) return null
    const lin = x.createLinearGradient(0, 0, W * 0.4, H)
    lin.addColorStop(0, '#0a1322')
    lin.addColorStop(0.46, '#14233c')
    lin.addColorStop(1, '#0b182c')
    x.fillStyle = lin
    x.fillRect(0, 0, W, H)
    const navy = x.createRadialGradient(W * 0.8, H * 1.05, 0, W * 0.8, H * 1.05, Math.max(W, H) * 0.9)
    navy.addColorStop(0, 'rgba(30,55,95,0.55)')
    navy.addColorStop(0.55, 'rgba(10,18,34,0)')
    x.fillStyle = navy
    x.fillRect(0, 0, W, H)
    const wash = x.createRadialGradient(W * 0.5, H * 0.3, 0, W * 0.5, H * 0.3, Math.max(W, H) * 0.5)
    wash.addColorStop(0, 'rgba(184,144,47,0.16)')
    wash.addColorStop(0.42, 'rgba(184,144,47,0)')
    x.fillStyle = wash
    x.fillRect(0, 0, W, H)
    const glow = x.createRadialGradient(W * 0.5, H * 0.44, 0, W * 0.5, H * 0.44, W * 0.34)
    glow.addColorStop(0, 'rgba(184,144,47,0.3)')
    glow.addColorStop(0.68, 'rgba(184,144,47,0)')
    x.fillStyle = glow
    x.fillRect(0, 0, W, H)
    return canvas.toDataURL('image/jpeg', 0.92)
  } catch {
    return null
  }
}

// ── public render + download ─────────────────────────────────────────────────
export function renderBlocks(p: Painter, blocks: Block[]): void {
  for (const b of blocks) {
    switch (b.k) {
      case 'cover':
        p.cover(b)
        p.d.addPage()
        p.y = M.t
        break
      case 'toc':
        p.toc(b.rows)
        break
      case 'section':
        p.sectionHead(b.num, b.title)
        break
      case 'insight':
        p.insight(b)
        break
      case 'table':
        p.table(b.cols, b.rows)
        break
      case 'note':
        p.note(b.text)
        break
      case 'readoutTable':
        p.readoutTable(b.cols, b.rows)
        break
      case 'readoutCard':
        p.readoutCard(b)
        break
      case 'lead':
        p.lead(b.paras)
        break
      case 'showHead':
        p.showHead(b.name, b.count)
        break
      case 'subhead':
        p.subhead(b.label)
        break
      case 'idea':
        p.idea(b)
        break
      case 'takeaways':
        p.takeaways(b.items)
        break
      case 'questions':
        p.questions(b.items)
        break
      case 'themes':
        p.themes(b.items)
        break
      case 'mentions':
        p.mentions(b.people, b.companies)
        break
      case 'quote':
        p.quote(b)
        break
      case 'moment':
        p.moment(b)
        break
      case 'qa':
        p.qa(b)
        break
      case 'sources':
        p.sources(b.rows)
        break
      case 'footer':
        p.footer(b.left, b.right)
        break
    }
  }
}

// Lay the blocks into a finished jsPDF document. TWO passes: pass 1 (a throwaway
// doc) records where each section lands so the TOC can print real page numbers;
// pass 2 renders for real with that map, then stamps the running footer. Runtime-
// agnostic — used by the browser download AND the server-side report generator.
function renderDoc(jsPDF: typeof JsPdf, blocks: Block[], logo: string | undefined, footerRight: string, title: string): JsPdf {
  const opts = { unit: 'pt' as const, format: 'a4', compress: true }
  // Pass 1 — probe: learn section → page.
  const record = new Map<string, number>()
  renderBlocks(new Painter(new jsPDF(opts), logo, { record }), blocks)
  // Pass 2 — real: resolve TOC page numbers, then stamp footers.
  const doc = new jsPDF(opts)
  doc.setProperties({ title })
  const painter = new Painter(doc, logo, { pageMap: record })
  renderBlocks(painter, blocks)
  stampFooters(doc, { left: FOOTER_LEFT, right: footerRight, skip: painter.landscapePages })
  return doc
}

async function buildAndSave(blocks: Block[], baseName: string, footerRight: string): Promise<void> {
  const [{ jsPDF }, { MUNSHOT_LOGO }] = await Promise.all([import('jspdf'), import('./brandLogo')])
  const doc = renderDoc(jsPDF, blocks, MUNSHOT_LOGO, footerRight, baseName)
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${sanitizeFilename(baseName)}.pdf`
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 10_000)
}

export function downloadWeeklyPdf(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): Promise<void> {
  return buildAndSave(weeklyBlocks(weekly, episodeById, podcastById), weeklyReportBaseName(weekly.rangeLabel), weekly.rangeLabel)
}

export function downloadSummaryPdf(episode: Episode, podcast?: Podcast): Promise<void> {
  return buildAndSave(episodeBlocks(episode, podcast), `${episode.title} — Munshot Summary`, longDate(episode.publishedAt))
}

// ── Server-side PDF bytes (no DOM) — the cron + on-demand hosted-PDF path ─────
// Generates the SAME document as the download, but returns raw bytes instead of
// triggering a browser save. The cover gradient falls back to a baked JPEG when
// there's no canvas (see makeCoverBg / COVER_BG_FALLBACK).
export async function weeklyPdfBytes(weekly: WeeklySummary, episodeById: ById<Episode>, podcastById: ById<Podcast>): Promise<ArrayBuffer> {
  const [{ jsPDF }, { MUNSHOT_LOGO }] = await Promise.all([import('jspdf'), import('./brandLogo')])
  const doc = renderDoc(jsPDF, weeklyBlocks(weekly, episodeById, podcastById), MUNSHOT_LOGO, weekly.rangeLabel, weeklyReportBaseName(weekly.rangeLabel))
  return doc.output('arraybuffer')
}
